// One descriptor per real V33 section renders a full editor; fields are grounded in the live schema and Voyage wiki, not inferred.
export const SECTIONS = {
  "story-overview": {
    key: "storySettings",
    label: "Story Overview",
    tab: "world",
    icon: "📖",
    kind: "singleton",
    blurb: "The premise the whole world hangs on, and how quests should feel.",
    fields: [
      {
        key: "worldBackground",
        label: "World background",
        type: "textarea",
        required: true,
        help: "Always in the AI's context; premise, current state, power structures, and where the player enters. 1200-5000 characters.",
      },
      { key: "questGenerationGuidance", label: "Quest generation guidance", type: "textarea", help: "Tone and structure for engine-generated quests; when to build an arc versus a standalone quest." },
    ],
  },
  "world-lore": {
    key: "worldLore",
    label: "World Lore",
    tab: "world",
    icon: "📜",
    kind: "record",
    keyField: "name",
    blurb: "Ambient context the narrator retrieves by meaning: creatures, history, customs.",
    pack: (entry) => ({ text: entry.text }),
    unpack: (name, value) => ({ name, text: value.text ?? "" }),
    fields: [
      { key: "name", label: "Title", type: "text", required: true, help: "Becomes the lore key; Title Case. Never shown to players." },
      { key: "text", label: "Lore", type: "textarea", required: true, help: "Dense, self-contained fact; first sentence names the subject. 500-800 characters reads best." },
    ],
  },
  "story-starts": {
    key: "storyStarts",
    label: "Story Starts",
    tab: "world",
    icon: "🚩",
    kind: "record",
    keyField: "name",
    blurb: "The opening scenarios a player can pick from.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea", required: true, help: "Player-facing blurb in the start selector; one to three sentences of situation and tone." },
      { key: "storyStart", label: "Opening narration", type: "textarea", required: true, help: "Draft narration the AI expands from. Present tense for the live scene, past tense for backstory." },
      { key: "locations", label: "Spawn locations", type: "refs", ref: "locations", required: true, help: "Candidate locations the player can spawn in." },
      { key: "locationAreas", label: "Spawn areas", type: "tags", required: true, help: "Area names within the spawn locations; each must match a defined area key." },
      { key: "isDefault", label: "Default start", type: "bool", advanced: true },
      { key: "firstQuest", label: "First quest seed", type: "textarea", advanced: true, help: "Vague thematic seed for the opening; free text, not a quest reference." },
      { key: "startingQuests", label: "Starting quests", type: "refs", ref: "quests", advanced: true, help: "Quest names flipped to available at game start." },
      { key: "startingPartyNPCs", label: "Starting party NPCs", type: "refs", ref: "npcs", advanced: true, help: "NPCs that join the party at the start." },
      { key: "startingItems", label: "Starting items", type: "json", advanced: true, help: "Array of { item, quantity } applied to every player of this start." },
      { key: "questGenerationGuidance", label: "Quest generation guidance", type: "textarea", advanced: true, help: "Per-start quest guidance layered on the global guidance." },
    ],
  },
  items: {
    key: "items",
    label: "Items",
    tab: "world",
    icon: "🎒",
    kind: "record",
    keyField: "name",
    blurb: "Objects players can carry, equip, and use.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key." },
      { key: "category", label: "Category", type: "enum", enumFrom: "itemSettings.itemCategories", required: true, help: "Must match a category in Item Settings." },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        required: true,
        help: "Describe the physical thing and what it does; reads like narration, not a tooltip. Common items under 150 characters.",
      },
      { key: "bonuses", label: "Bonuses", type: "json", required: true, help: "Array of { type, variable, value } modifiers; use [] for none." },
      { key: "slot", label: "Equip slot", type: "text", advanced: true, help: "Optional; must match a slot in Item Settings when present." },
      { key: "mediaContent", label: "Readable content", type: "textarea", advanced: true, help: "Full text shown when reading the item; required for Readable items, omit otherwise." },
    ],
  },
  factions: {
    key: "factions",
    label: "Factions",
    tab: "world",
    icon: "🏳️",
    kind: "record",
    keyField: "name",
    blurb: "Organisations that shape the world. Each needs a matching lore entry.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key." },
      { key: "basicInfo", label: "Public info", type: "textarea", required: true, help: "The public face: what it is, its reach, how it operates, how outsiders see it. 400-800 characters." },
      { key: "factionType", label: "Type", type: "enum", options: ["minor", "major"], required: true, help: "major = multi-region, civilisation-level; minor = small local group." },
      { key: "hiddenInfo", label: "Hidden info", type: "textarea", advanced: true, help: "The truth that contradicts the public face; narrator-only, discovered through play." },
      { key: "known", label: "Known at start", type: "bool", advanced: true, help: "Defaults true; set false for secret organisations discovered through play." },
    ],
  },
  npcs: {
    key: "npcs",
    label: "NPCs",
    tab: "world",
    icon: "🧑‍🤝‍🧑",
    kind: "record",
    keyField: "name",
    blurb: "Named characters with personality and place in the world.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key." },
      { key: "type", label: "NPC type", type: "ref", ref: "npcTypes", required: true, help: "An NPC Types key for a shared damage profile, or empty for a unique character." },
      { key: "currentLocation", label: "Current location", type: "ref", ref: "locations", required: true, help: "Location key where the NPC is." },
      { key: "currentArea", label: "Current area", type: "text", required: true, help: "Area key within that location; omit only if the location has no areas." },
      { key: "basicInfo", label: "Description", type: "textarea", help: "Narrator-visible: role, one specific appearance detail, current situation. 250-600 characters." },
      { key: "hiddenInfo", label: "Hidden info", type: "textarea", advanced: true, help: "What the player hasn't discovered yet; revealed only through play." },
      { key: "personality", label: "Personality", type: "tags", help: "Behavioural phrases, not adjectives. 4-10 entries." },
      {
        key: "abilities",
        label: "Abilities",
        type: "tags",
        advanced: true,
        help: "Prose capability descriptions for the AI; last entry is a fighting-style summary. Not the top-level Abilities section.",
      },
      { key: "properName", label: "Proper name", type: "text", advanced: true, help: "True name when the NPC goes by an alias or street name." },
      { key: "gender", label: "Gender", type: "text", advanced: true },
      { key: "faction", label: "Faction", type: "ref", ref: "factions", advanced: true },
      {
        key: "tier",
        label: "Combat tier",
        type: "enum",
        options: ["trivial", "weak", "average", "strong", "elite", "boss", "mythic"],
        advanced: true,
        help: "Controls HP scaling, damage output, and intent complexity.",
      },
      { key: "vulnerabilities", label: "Vulnerabilities", type: "tags", advanced: true, help: "Damage types at 1.5x; unions with the NPC type's arrays." },
      { key: "resistances", label: "Resistances", type: "tags", advanced: true, help: "Damage types at 0.5x." },
      { key: "immunities", label: "Immunities", type: "tags", advanced: true, help: "Damage types at 0x." },
      { key: "visualDescription", label: "Visual description", type: "textarea", advanced: true, help: "Read only by the image generator; appearance the narrator should not lock in." },
      { key: "portraitUrl", label: "Portrait", type: "image", advanced: true, help: "Portrait image URL; skips portrait generation." },
      {
        key: "detailType",
        label: "Detail type",
        type: "enum",
        options: ["basic", "detailed"],
        advanced: true,
        help: "Defaults to detailed (authored content preserved); basic lets the engine flesh it out.",
      },
      { key: "level", label: "Level", type: "number", advanced: true, help: "Explicit level; if omitted the engine rolls near party level and clamps to the location range." },
      { key: "hpMax", label: "Max HP", type: "number", advanced: true, help: "Explicit max HP; overrides level/tier scaling and health multiplier." },
      { key: "hpCurrent", label: "Current HP", type: "number", advanced: true },
      { key: "healthMultiplier", label: "Health multiplier", type: "number", advanced: true, help: "Scalar on calculated max HP; ignored when max HP is set." },
      { key: "known", label: "Known at start", type: "bool", advanced: true, help: "Set false for NPCs discovered through play." },
    ],
  },
  regions: {
    key: "regions",
    label: "Regions",
    tab: "world",
    icon: "🗺️",
    kind: "record",
    keyField: "name",
    blurb: "Grid cells of the map. Adjacent regions differ by one in x or y.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key." },
      { key: "basicInfo", label: "Description", type: "textarea", required: true, help: "Geographic description: terrain, climate, landmarks, who lives here. Not national or political lore." },
      { key: "x", label: "Grid X", type: "number", required: true, help: "Grid cell X; adjacent regions differ by exactly 1. East is +x." },
      { key: "y", label: "Grid Y", type: "number", required: true, help: "Grid cell Y; north is +y." },
      { key: "realm", label: "Realm", type: "ref", ref: "realms", help: "Realm this region belongs to; almost always set or it won't appear on the realm map." },
      { key: "factions", label: "Factions present", type: "refs", ref: "factions", advanced: true, help: "Factions with broad, region-wide presence." },
      { key: "npcLevelRange", label: "NPC level range", type: "json", advanced: true, help: "{ min, max } band for AI-generated NPCs in this region." },
      { key: "known", label: "Known at start", type: "bool", advanced: true, help: "Set false for regions discovered through play." },
      { key: "imageUrl", label: "Image", type: "image", advanced: true, help: "Banner or map image URL; accepted but not officially supported." },
    ],
  },
  locations: {
    key: "locations",
    label: "Locations",
    tab: "world",
    icon: "📍",
    kind: "record",
    keyField: "name",
    blurb: "Named places inside regions: towns, posts, dungeons.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key." },
      { key: "basicInfo", label: "Description", type: "textarea", required: true, help: "Public description: what the place is, who is here, the dominant feeling. 2-3 sentences." },
      { key: "region", label: "Region", type: "ref", ref: "regions", required: true, help: "Region this location belongs to." },
      { key: "x", label: "Offset X", type: "number", required: true, help: "Local offset from the region centre, -50 to +50." },
      { key: "y", label: "Offset Y", type: "number", required: true, help: "Local offset from the region centre, -50 to +50." },
      { key: "radius", label: "Map radius", type: "number", required: true, help: "Map circle radius; 2-6 typical. Don't overlap circles." },
      { key: "complexityType", label: "Complexity", type: "enum", options: ["simple", "complex", "wilderness"], required: true, help: "complex = multiple areas connected by paths." },
      {
        key: "detailType",
        label: "Detail type",
        type: "enum",
        options: ["basic", "detailed"],
        required: true,
        help: "Determines whether quests here use spatial relationship or a pinned quest location.",
      },
      { key: "areas", label: "Areas", type: "json", advanced: true, help: "Map of area name to { description, paths }; paths must be symmetric." },
      { key: "hiddenInfo", label: "Hidden info", type: "textarea", advanced: true, help: "The truth beneath the surface; drives AI behaviour, never shown to players." },
      { key: "factions", label: "Factions present", type: "refs", ref: "factions", advanced: true, help: "Factions with a presence at this location." },
      { key: "visualTags", label: "Visual tags", type: "tags", advanced: true, help: "Visual descriptors used for image generation." },
      { key: "npcLevelRange", label: "NPC level range", type: "json", advanced: true, help: "{ min, max } band overriding the region's for NPCs generated here." },
      { key: "known", label: "Known at start", type: "bool", advanced: true, help: "Set false for locations discovered through play." },
      { key: "imageUrl", label: "Image", type: "image", advanced: true, help: "Banner or map image URL; accepted but not officially supported." },
    ],
  },
  quests: {
    key: "quests",
    label: "Quests",
    tab: "world",
    icon: "❓",
    kind: "record",
    keyField: "name",
    advancedSection: true,
    blurb: "Authored objectives. Each needs a trigger pointing to it to be reachable.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key." },
      { key: "questSource", label: "Quest source", type: "text", required: true, help: "Who hands out the quest; free-form string." },
      { key: "questStatement", label: "Quest statement", type: "textarea", required: true, help: "Full scene context: who, what, where, and how success is judged. 100-500 characters." },
      { key: "mainObjective", label: "Main objective", type: "text", required: true, help: "Player-visible goal; start with an imperative verb." },
      { key: "completionCondition", label: "Completion condition", type: "text", required: true, help: "What 'done' looks like in plain language; be specific." },
      { key: "detailType", label: "Detail type", type: "enum", options: ["basic", "detailed"], required: true, help: "detailed pins to a quest location; basic uses a spatial relationship." },
      { key: "questLocation", label: "Quest location", type: "ref", ref: "locations", advanced: true, help: "Required when detailed; must be a location key, not a region." },
      {
        key: "spatialRelationship",
        label: "Spatial relationship",
        type: "enum",
        options: ["existingLocalArea", "newLocalArea", "nearbyNewLocation", "distantNewLocation", "existingLocationNewAreas"],
        advanced: true,
        help: "Required when basic; where the quest takes place relative to the giver.",
      },
      { key: "conclusive", label: "Conclusive", type: "bool", advanced: true, help: "Ends the main arc when completed." },
      { key: "questDesignBrief", label: "Quest design brief", type: "textarea", advanced: true, help: "Authoring notes on how the quest should feel and run; not player-visible." },
      { key: "questType", label: "Quest type", type: "text", advanced: true, help: "Free-form label for organisation only; not read by the engine." },
    ],
  },
  "npc-types": {
    key: "npcTypes",
    label: "NPC Types",
    tab: "world",
    icon: "🧬",
    kind: "record",
    keyField: "name",
    advancedSection: true,
    blurb: "Reusable templates: a species or profession's damage profile and behaviour.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key." },
      {
        key: "description",
        label: "Behaviour",
        type: "textarea",
        required: true,
        help: "Baseline behaviour template: how the type acts socially and in combat, what motivates it, how it sees the player.",
      },
      { key: "vulnerabilities", label: "Vulnerabilities", type: "tags", required: true, help: "Damage types taken at 1.5x; must match strings in Combat Settings damage types." },
      { key: "resistances", label: "Resistances", type: "tags", required: true, help: "Damage types taken at 0.5x." },
      { key: "immunities", label: "Immunities", type: "tags", required: true, help: "Damage types taken at 0x." },
    ],
  },
  realms: {
    key: "realms",
    label: "Realms",
    tab: "world",
    icon: "🌐",
    kind: "record",
    keyField: "name",
    advancedSection: true,
    blurb: "Top-level containers. Most worlds need exactly one.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must be byte-identical to the map key; region.realm references resolve by it." },
      { key: "basicInfo", label: "Description", type: "textarea", required: true, help: "Top-level description of the world, country, or dimension containing the regions." },
      { key: "known", label: "Accessible at start", type: "bool", help: "Defaults true; revealing a realm does not reveal its regions or locations." },
    ],
  },

  attributes: {
    key: "attributeSettings",
    label: "Attributes",
    tab: "mechanics",
    icon: "💪",
    kind: "singleton",
    blurb: "The core stats that drive every roll. Names must be lowercase.",
    fields: [
      { key: "attributeNames", label: "Attributes", type: "tags", required: true, help: "Lowercase names, e.g. strength, dexterity. They tell the AI which attribute applies to an action." },
      { key: "startingAttributeValue", label: "Starting value", type: "number", required: true, help: "The base value every attribute starts at before trait modifiers." },
      { key: "startingAttributePoints", label: "Points to spend", type: "number", required: true },
      { key: "maxStartingAttribute", label: "Starting cap", type: "number", required: true },
      { key: "attributeBonusModifier", label: "Attribute bonus modifier", type: "number", required: true, help: "Per-point weight an attribute adds to a skill check above the baseline." },
      { key: "lowAttributeThreshold", label: "Low threshold", type: "number", required: true, help: "Attribute score below which a character counts as low in that attribute." },
      {
        key: "lowAttributeTraits",
        label: "Low-attribute traits",
        type: "json",
        required: true,
        help: "Map of attribute name to a trait applied when the score falls below the low threshold. Use {} to disable.",
      },
      { key: "attributeStatModifiers", label: "Stat modifiers", type: "json", required: true, help: "Map of attribute to a resource boost: variable (resource name) and amount (boost per point)." },
      { key: "attributeDamageModifiers", label: "Damage modifiers", type: "json", advanced: true, help: "Map of attribute to a percent bonus on outgoing damage per point." },
      { key: "attributeDamageReductionModifiers", label: "Damage reduction modifiers", type: "json", advanced: true, help: "Map of attribute to a percent reduction of incoming damage per point." },
    ],
  },
  resources: {
    key: "resourceSettings",
    label: "Resources",
    tab: "mechanics",
    icon: "🔋",
    kind: "record",
    keyField: "name",
    blurb: "Tracked bars: health, mana, stamina. Up to nine.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must match the map key exactly. A single lowercase word, no spaces." },
      { key: "initialValue", label: "Start value", type: "number", required: true, help: "Starting value before attribute modifiers." },
      { key: "maxValue", label: "Max value", type: "number", required: true, help: "Hard cap. Avoid 0." },
      { key: "rechargeRate", label: "Per-turn recharge", type: "number", required: true, help: "Whole number. Negative values drain the resource each turn." },
      { key: "restRechargeMultiplier", label: "Rest recharge", type: "number", required: true, help: "Fraction restored on rest: 1 full, 0.5 half, 0 none." },
      { key: "gainPerLevel", label: "Gain per level", type: "number", required: true, help: "Max increase per level-up. Use 0 if non-scaling." },
      { key: "color", label: "Bar colour", type: "color", required: true },
      { key: "isHealth", label: "Is health", type: "bool", help: "True for the HP bar only. Exactly one resource." },
      { key: "usageInstructions", label: "Narrator rules", type: "textarea", help: "Markdown for the AI: what raises and lowers it, cost tiers, when not to deduct it." },
    ],
  },
  skills: {
    key: "skills",
    label: "Skills",
    tab: "mechanics",
    icon: "🎯",
    kind: "record",
    keyField: "name",
    blurb: "Rolled actions. Combat skills add attribute-scaled damage.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must match the map key exactly." },
      { key: "type", label: "Type", type: "text", required: true, help: "Must match a key in Skill Settings' type bonuses. Conventionally combat or utility; only combat scales damage." },
      { key: "attribute", label: "Attribute", type: "enum", enumFrom: "attributeSettings.attributeNames", required: true, help: "Must match a name in Attributes." },
      { key: "description", label: "Description", type: "textarea", required: true, help: "Primary AI guidance: what it covers and DC thresholds." },
      { key: "startingItems", label: "Starting items", type: "json", required: true, advanced: true, help: "Array of { item, quantity } granted when the skill is learned. Use [] if none." },
    ],
  },
  traits: {
    key: "traits",
    label: "Traits",
    tab: "mechanics",
    icon: "🧩",
    kind: "record",
    keyField: "name",
    blurb: "Character-creation choices: race, class, background, perks.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must match the map key exactly." },
      { key: "description", label: "Description", type: "textarea", required: true, help: "Player-facing, shown in the character creator." },
      { key: "quirk", label: "Quirk", type: "textarea", required: true, help: "The narrator's working reference for the trait during play." },
      { key: "skills", label: "Skill modifiers", type: "json", required: true, advanced: true, help: "Array of { skill, modifier }. Required even if []." },
      { key: "attributes", label: "Attribute modifiers", type: "json", required: true, advanced: true, help: "Array of { attribute, modifier }. Required even if []." },
      { key: "resources", label: "Resource modifiers", type: "json", required: true, advanced: true, help: "Array of { resource, modifier }. Required even if []." },
      { key: "startingItems", label: "Starting items", type: "json", required: true, advanced: true, help: "Array of { item, quantity }. Negative quantity removes items. Required even if []." },
      { key: "abilities", label: "Grants abilities", type: "refs", ref: "abilities", required: true, advanced: true, help: "Abilities granted to anyone who takes this trait. Required even if []." },
      { key: "unlockedBy", label: "Unlocked by", type: "refs", ref: "traits", required: true, advanced: true, help: "Reserved prerequisite gate (not yet enforced). Required even if []." },
      { key: "excludedBy", label: "Excluded by", type: "refs", ref: "traits", required: true, advanced: true, help: "Reserved mutual-exclusion (not yet enforced). Required even if []." },
      { key: "vulnerabilities", label: "Vulnerabilities", type: "tags", advanced: true, help: "Damage types taken at 1.5x. Must match combat damage types." },
      { key: "resistances", label: "Resistances", type: "tags", advanced: true, help: "Damage types taken at 0.5x." },
      { key: "immunities", label: "Immunities", type: "tags", advanced: true, help: "Damage types taken at 0x." },
    ],
  },
  "trait-categories": {
    key: "traitCategories",
    label: "Trait Categories",
    tab: "mechanics",
    icon: "🗂️",
    kind: "record",
    keyField: "name",
    advancedSection: true,
    blurb: "Group traits and cap how many a player can pick.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must match the map key exactly." },
      { key: "maxSelections", label: "Max selections", type: "number", required: true, help: "How many traits the player can pick. 1 is single-pick. Avoid 0." },
      { key: "traits", label: "Traits", type: "refs", ref: "traits", required: true, help: "Trait names that belong to this category." },
    ],
  },
  "item-settings": {
    key: "itemSettings",
    label: "Item Settings",
    tab: "mechanics",
    icon: "⚙️",
    kind: "singleton",
    blurb: "Currency and the categories items can belong to.",
    fields: [
      { key: "currencyName", label: "Currency name", type: "text", required: true },
      { key: "itemCategories", label: "Categories", type: "tags", required: true, help: "The item categories that exist in your world." },
      { key: "itemSlots", label: "Equipment slots", type: "json", required: true, help: "Array of { slot, category, quantity }. Slot and category usually match." },
      { key: "startingItems", label: "Starting items", type: "json", required: true, help: "Array of { item, quantity } given to every player regardless of trait or start." },
    ],
  },
  abilities: {
    key: "abilities",
    label: "Abilities",
    tab: "mechanics",
    icon: "✨",
    kind: "record",
    keyField: "name",
    advancedSection: true,
    blurb: "Named actions: spells, techniques, special maneuvers.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Must match the map key exactly. Player input matches case-insensitively." },
      { key: "description", label: "Description", type: "textarea", required: true, help: "Narrative plus a plain effect statement; the narrator reads this as the ability's effect." },
      { key: "bonus", label: "Check bonus", type: "number", required: true, help: "Shown in-game as Power. Added flat to the check. Set equal to the skill requirement." },
      { key: "cooldown", label: "Cooldown (turns)", type: "number", required: true, help: "Turns before reuse. Default 0." },
      {
        key: "requirements",
        label: "Requirements",
        type: "json",
        required: true,
        advanced: true,
        help: "Array of gates: { type, variable, amount }. type is skill, attribute, resource, trait, or characterLevel.",
      },
    ],
  },

  "ai-instructions": {
    key: "aiInstructions",
    label: "AI Instructions",
    tab: "ai",
    icon: "🤖",
    kind: "recordmap",
    blurb: "Per-task guidance the narrator and generators follow. Each task holds named instruction blocks of markdown.",
    limits: { perKey: 5000, perSection: 20000 },
    tasks: [
      "generateStory",
      "generateInitialStart",
      "generateActionInfo",
      "generateCharacterBackground",
      "generateNPCIntents",
      "generateNewNPC",
      "generateNPCDetails",
      "generateNPCUpdates",
      "generateLocationDetails",
      "generateRegionDetails",
      "generateFactionDetails",
      "generateEncounters",
      "ItemGenerationAndUsage",
      "summarization",
      "generateLearnedAbilities",
      "generateDMResponse",
      "generateResourceUpdates",
    ],
  },
  "image-prompts": {
    key: "imagePromptConfiguration",
    label: "Image Prompts",
    tab: "ai",
    icon: "🖼️",
    kind: "singleton",
    blurb: "Art-direction text appended when generating portraits, locations, and regions.",
    fields: [
      { key: "npcs", label: "NPC portrait prompt", type: "textarea", help: "Author text layered onto every NPC portrait request to lock style and framing." },
      { key: "locations", label: "Location image prompt", type: "textarea", help: "Author text layered onto every location art request for camera, mood, and style." },
      { key: "regions", label: "Region image prompt", type: "textarea", help: "Author text layered onto every region art request, typically broad landscape framing." },
      { key: "characterLoraEnabled", label: "Voyage style for characters", type: "bool", help: "Apply Voyage's default character art style on top of your NPC prompt; on by default." },
      { key: "locationLoraEnabled", label: "Voyage style for locations", type: "bool", help: "Apply Voyage's default location art style on top of your location and region prompts; on by default." },
    ],
  },
  "narrator-style": {
    key: "narratorStyle",
    label: "Narrator Style",
    tab: "ai",
    icon: "🗣️",
    kind: "scalar",
    scalarType: "textarea",
    blurb: "The narrator's voice: tense, person, vocabulary register, NPC behavioural defaults, pacing, and explicit prohibitions. Leave empty for default narration.",
  },

  "premade-characters": {
    key: "premadeCharacters",
    label: "Premade Characters",
    tab: "world",
    icon: "🎭",
    kind: "list",
    keyField: "name",
    blurb: "Ready-made player characters offered at the start.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "gender", label: "Gender", type: "text", required: true },
      { key: "description", label: "Description", type: "textarea", required: true, help: "Shown at character select and sent as the Background to the story AI each turn; lead with a hook." },
      { key: "traits", label: "Traits", type: "refs", ref: "traits", help: "Trait keys; how the premade gets attributes, skills, resources, abilities, and starting items." },
      { key: "portraitUrl", label: "Portrait", type: "image", advanced: true, help: "Portrait URL used as-is; skips portrait generation." },
      { key: "replacesNpc", label: "Replaces NPC", type: "ref", ref: "npcs", advanced: true, help: "Named NPC fully removed from game state when this premade is chosen." },
    ],
  },
  "game-modes": {
    key: "gameModes",
    label: "Game Modes",
    tab: "world",
    icon: "🕹️",
    kind: "record",
    keyField: "name",
    blurb: "Difficulty and tone presets a player can pick for a run.",
    fields: [
      { key: "name", label: "Name", type: "text", required: true, help: "Display name shown when selecting a mode; matches the entry key by convention." },
      { key: "description", label: "Description", type: "textarea", required: true, help: "Short summary shown to the player alongside the name during selection." },
      { key: "instructions", label: "Instructions", type: "textarea", required: true, help: "Markdown story brief appended to initial-start and story generation for the whole run." },
      { key: "difficulty", label: "Difficulty", type: "text", advanced: true, help: "Free-form; standard values very easy/easy/medium/hard/very hard show difficulty dots." },
      { key: "askTheNarratorPrompt", label: "Ask-the-narrator prompt", type: "textarea", advanced: true, help: "Opening message shown at the top of the narrator chat when the session begins." },
    ],
  },

  "combat-settings": {
    key: "combatSettings",
    label: "Combat Settings",
    tab: "mechanics",
    icon: "⚔️",
    kind: "singleton",
    advancedSection: true,
    blurb: "Damage model, XP, and combat-wide numbers.",
    fields: [
      { key: "damageTypes", label: "Damage types", type: "tags", required: true, help: "Canonical list of valid damage types. Matching is exact and case-sensitive; use lowercase." },
      { key: "baseCombatXP", label: "Base combat XP", type: "number", required: true, help: "Base XP for defeating an enemy." },
      { key: "minCombatXP", label: "Minimum combat XP", type: "number", required: true, help: "Floor on XP awarded for a combat victory." },
      { key: "abilityBonus", label: "Default ability bonus", type: "number", required: true, help: "Default Power for abilities that define no bonus. Not a multiplier." },
      {
        key: "abilityCooldown",
        label: "Default ability cooldown",
        type: "number",
        required: true,
        help: "Default cooldown for abilities with none, and the minimum gap before learning a new ability.",
      },
      { key: "npcDailyHealingAmount", label: "NPC daily healing", type: "number", required: true, help: "HP NPCs recover per in-game day." },
    ],
  },
  "skill-settings": {
    key: "skillSettings",
    label: "Skill Settings",
    tab: "mechanics",
    icon: "🎚️",
    kind: "singleton",
    advancedSection: true,
    blurb: "Caps, XP rewards, and how skills are learned.",
    fields: [
      { key: "maxSkillLevel", label: "Max skill level", type: "number", required: true, help: "Caps how high a skill can be trained. Must equal max success contribution." },
      { key: "maxSkillSuccessLevel", label: "Max success contribution", type: "number", required: true, help: "Caps how much any single contribution adds to a check. Must equal max skill level." },
      { key: "skillXPRewards", label: "Skill XP rewards", type: "json", required: true, help: "Map of size bucket (small/medium/large/huge) to XP per successful use." },
      { key: "skillTypeDifficultyBonus", label: "Skill type bonuses", type: "json", required: true, help: "Map of skill type to a flat bonus on its checks. Keys must match skill types." },
      { key: "startingXPToLevelUpSkill", label: "Starting XP to level up", type: "number", required: true, help: "XP needed for the first skill level." },
      { key: "additionalXPRequiredPerSkillLevel", label: "Extra XP per level", type: "number", required: true, help: "Additional XP required per level beyond the first." },
      { key: "baseChanceToLearnNewSkill", label: "Learn chance", type: "number", required: true, help: "Probability of learning a new skill on first attempt. 0.1 is 10 percent." },
      { key: "newSkillGenerationEnabled", label: "Allow new skills", type: "bool", required: true, help: "Whether the engine may invent new skills during play." },
      { key: "skillBonusModifier", label: "Skill bonus modifier", type: "number", required: true, advanced: true, help: "Weight applied to skill level in the check formula." },
      {
        key: "skillLearningBonusModifier",
        label: "Learn bonus modifier",
        type: "number",
        required: true,
        advanced: true,
        help: "Added to learn chance per attribute point. Set this and learn chance to 0 to lock the skill set.",
      },
      { key: "xpFromNewSkill", label: "XP from new skill", type: "number", required: true, advanced: true, help: "Character XP granted when a new skill is learned." },
      { key: "trainingCooldown", label: "Training cooldown", type: "number", required: true, advanced: true, help: "Ticks between training sessions." },
      { key: "charXPPerSkillLevel", label: "Char XP per skill level", type: "number", required: true, advanced: true, help: "Character XP gained per skill level." },
      { key: "baseXPFromSkillUpgrade", label: "Base XP from upgrade", type: "number", required: true, advanced: true, help: "Base character XP from upgrading a skill." },
    ],
  },
  "location-settings": {
    key: "locationSettings",
    label: "Location Settings",
    tab: "mechanics",
    icon: "🧭",
    kind: "singleton",
    advancedSection: true,
    blurb: "Map sizing and travel-related defaults.",
    fields: [
      { key: "regionSize", label: "Region size", type: "number", required: true, help: "Width of each region in coordinate units; location x/y offsets are relative to this." },
      { key: "simpleRadius", label: "Simple location radius", type: "number", required: true, help: "Map footprint of a simple-complexity location." },
      { key: "complexRadius", label: "Complex location radius", type: "number", required: true, help: "Map footprint of a complex-complexity location, which is larger." },
      { key: "regionLocationCount", label: "Locations per region", type: "number", required: true, help: "Target points of interest per AI-generated region." },
      { key: "avgTravelDistance", label: "Average travel distance", type: "number", required: true, help: "Average distance between destinations; keep at most region size." },
      { key: "minTravelDistance", label: "Minimum travel distance", type: "number", required: true, help: "Minimum distance between locations so travel is never instantaneous." },
      { key: "regionFactionCount", label: "Factions per region", type: "number", required: true, help: "How many factions the engine places in AI-generated regions." },
      { key: "newRegionGenerationEnabled", label: "Allow new regions", type: "bool", required: true, help: "Whether the AI can create new regions during play." },
      { key: "encountersEnabled", label: "Encounters enabled", type: "bool", required: true, help: "Enables the random encounter system." },
      {
        key: "regionMapBorderFeatheringEnabled",
        label: "Feather region map borders",
        type: "bool",
        advanced: true,
        help: "Fade region map edges; turn off to align region images into one seamless map.",
      },
    ],
  },
  "other-settings": {
    key: "otherSettings",
    label: "Other Settings",
    tab: "mechanics",
    icon: "🔩",
    kind: "singleton",
    advancedSection: true,
    blurb: "Level curve and miscellaneous run settings.",
    fields: [
      { key: "startingCharacterLevelUpRequirement", label: "First level-up XP", type: "number", required: true, help: "Base XP required to reach the next character level." },
      { key: "extraRequiredXPPerCharacterLevel", label: "Extra XP per level", type: "number", required: true, help: "Additional XP added to the requirement for each subsequent level." },
      { key: "maxCharacterLevel", label: "Max character level", type: "number", required: true, help: "The character level cap." },
      { key: "npcHealthPerLevel", label: "NPC health per level", type: "number", required: true, help: "Per-level HP scaling for NPCs." },
      { key: "npcMinHealth", label: "NPC minimum health", type: "number", required: true, help: "Floor on generated NPC health." },
    ],
  },
  "death-settings": {
    key: "death",
    label: "Death",
    tab: "mechanics",
    icon: "💀",
    kind: "singleton",
    advancedSection: true,
    blurb: "Whether death is permanent and how it is narrated.",
    fields: [
      { key: "permadeath", label: "Permadeath", type: "bool", required: true, help: "Whether death is permanent." },
      { key: "instructions", label: "Instructions", type: "textarea", required: true, help: "Prose fed to the narrator describing the downing and recovery process." },
    ],
  },
  "name-filter-settings": {
    key: "nameFilterSettings",
    label: "Name Filters",
    tab: "mechanics",
    icon: "🔤",
    kind: "record",
    keyField: "name",
    blurb: "Names the narrator should avoid, with replacements.",
    pack: (entry) => ({ replacements: entry.replacements ?? [] }),
    unpack: (name, value) => ({ name, replacements: value.replacements ?? [] }),
    fields: [
      { key: "name", label: "Name or fragment", type: "text", required: true, help: "Generated name (or fragment) to replace; becomes the entry key." },
      { key: "replacements", label: "Replacements", type: "tags", required: true, help: "Lore-appropriate substitutes; a single empty string deletes the name outright." },
    ],
  },
  "tip-settings": {
    key: "tipSettings",
    label: "Tips",
    tab: "mechanics",
    icon: "💡",
    kind: "singleton",
    advancedSection: true,
    blurb: "Loading tips and how often they show.",
    fields: [
      { key: "tips", label: "Tips", type: "tags", required: true, help: "Player-facing messages shown periodically; the only section that speaks to the player." },
      { key: "tipDisplayEnabled", label: "Show tips", type: "bool", required: true, help: "Whether tips are displayed at all." },
      { key: "tipTurnInterval", label: "Turn interval", type: "number", required: true, help: "Turns between tip displays." },
      { key: "tipMinimumTurns", label: "Minimum turns", type: "number", required: true, help: "Lower bound on the turn gap before a tip can show." },
      { key: "tipMaximumTurns", label: "Maximum turns", type: "number", required: true, help: "Upper bound on the turn gap between tips." },
    ],
  },
  "random-names": {
    key: "randomNames",
    label: "Random Names",
    tab: "mechanics",
    icon: "🎲",
    kind: "singleton",
    advancedSection: true,
    blurb: "Name pools the generator draws from.",
    fields: [
      { key: "male", label: "Male names", type: "tags", required: true, help: "Male-register name pool for the randomize button and AI NPC names; keep at least 10." },
      { key: "female", label: "Female names", type: "tags", required: true, help: "Female-register name pool for the randomize button and AI NPC names; keep at least 10." },
    ],
  },
  "character-creation-music": {
    key: "characterCreationMusic",
    label: "Character Creation Music",
    tab: "mechanics",
    icon: "🎵",
    kind: "scalar",
    scalarType: "enum",
    options: ["fantasy", "nonfantasy"],
    advancedSection: true,
    blurb: "Background music during character creation. Leave unset to play none.",
  },

  "author-seeds": {
    key: "authorSeeds",
    label: "Author Seeds",
    tab: "archetypes",
    icon: "✍️",
    kind: "stringmap",
    blurb: "Named NPC-writing-tone presets. Each key is a display label; its value is a multi-line directive. One is picked at random per run for strong-and-above NPCs.",
  },
  "character-archetypes": {
    key: "characterArchetypes",
    label: "Character Archetypes",
    tab: "archetypes",
    icon: "👤",
    kind: "stringmap",
    blurb: "Keyed personality scaffolds consulted when generating unnamed characters. Each block uses Drives, Traits, Morality, Relationships. Keep at least one entry.",
  },
  "location-archetypes": {
    key: "locationArchetypes",
    label: "Location Archetypes",
    tab: "archetypes",
    icon: "🏚️",
    kind: "stringmap",
    blurb: "Tone directions for describing a location. Each block uses Atmosphere, Tensions, Patterns, Secrets. Keep at least one entry.",
  },
  "region-archetypes": {
    key: "regionArchetypes",
    label: "Region Archetypes",
    tab: "archetypes",
    icon: "🗺️",
    kind: "stringmap",
    blurb: "Tone directions for describing a region. Each block uses Geography, Dynamics, History, Atmosphere. Keep at least one entry.",
  },
  "encounter-elements": {
    key: "encounterElements",
    label: "Encounter Elements",
    tab: "archetypes",
    icon: "⚡",
    kind: "stringmap",
    blurb: "A palette of scenarios the AI draws from when framing random encounters. Free-form one-paragraph entries.",
  },
};

export const SIDEBAR = [
  {
    group: "Studio",
    note: "Saved to your account",
    items: [
      { id: "overview", label: "Overview", icon: "🌐", kind: "panel" },
      { id: "mods", label: "Mod Library", icon: "🧩", kind: "panel" },
    ],
  },
  {
    group: "Engine",
    note: "Replaceable · your rules",
    items: [
      { id: "systems", label: "Game Systems", icon: "🎲", kind: "panel" },
      { id: "events", label: "Events", icon: "⚡", kind: "panel" },
      { id: "ui-builder", label: "UI Builder", icon: "🎛️", kind: "panel" },
    ],
  },
  { group: "World", note: "Content you author", items: sectionsForTab("world") },
  { group: "Mechanics", note: "Rules and numbers", items: sectionsForTab("mechanics") },
  { group: "AI", note: "How the narrator behaves", items: sectionsForTab("ai") },
  { group: "Archetypes", note: "Generator building blocks", items: sectionsForTab("archetypes") },
];

function sectionsForTab(tab) {
  return Object.entries(SECTIONS)
    .filter(([, section]) => section.tab === tab)
    .map(([id, section]) => ({ id, label: section.label, icon: section.icon, kind: "section", advanced: section.advancedSection }));
}
